### ISSUE TITLE
[原神] 安卓14版本无权限读去Android/data 

### ISSUE THREAD

**Issue by diaolingge** [fanajing/HuanFuQi#2]
安卓14更新后需要ADB权限进行授予权限 希望能加入Shizuku授予权限读取Data = =

**Comment by fanajing** [comment]
我觉得你的提议很不错，后续我会考虑加入，因为我的技术比较弱，所以可能需要一段时间，如果你想实践的话可以直接拿去使用。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanajing/HuanFuQi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月23日(星期五) 上午8:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[fanajing/HuanFuQi] [原神] 安卓14版本无权限读去Android/data  (Issue #2)





 
安卓14更新后需要ADB权限进行授予权限 希望能加入Shizuku授予权限读取Data = =
